New function to fetch quotes (call endpoint with function GLOBAL_QUOTE)
ricardo93borges/alphavantage-wrapper-ts pull request #29
Opened 2023-02-27 07:16 UTC by volpatorafael

2023-03-02 17:37 UTC, ricardo93borges commented on test/e2e/stock-time-series/stock-time-series.test.ts
> +describe('#quote', () => {
please put this test inside the `describe('StockTimeSeries', () => { ` block, right after the `describe('#monthlyAdjusted', () => {` block, so the `quote `test can have access to the `api` object

2023-03-02 17:39 UTC, ricardo93borges commented on src/stock-time-series/StockTimeSeries.ts
> +  async quote(quoteDTO: QuoteDTO): Promise<QuoteResponse> {
please add the unit tests for this method, the tests should be something similar to the `search `method unit tests

2023-03-02 20:15 UTC, ricardo93borges commented on src/stock-time-series/StockTimeSeries.ts
> +    try {
Also, update the README with this new function, please.

2023-03-13 14:20 UTC, ricardo93borges requested changes
The datatype description should be this one:

**datatype**: (optional) By default, datatype=json. Strings json and csv are accepted with the following specifications: json returns the quote data in JSON format; csv returns the quote data as a CSV (comma separated value) file.

2023-03-13 14:24 UTC, volpatorafael commented on README.md
> +2. **datatype**: (optional) By default, datatype=json. Strings json and csv are accepted with the following specifications: json returns the intraday time series in JSON format; csv returns the time
updated

2023-03-13 14:25 UTC, volpatorafael commented on test/unit/stock-time-series/stock-time-series.test.ts
> +      expect(result).toEqual([
Yes, the commit b6082b5e72806c6cce39147ac17faeaebbf9f27f fixed it

2023-03-13 15:47 UTC, merged