feat(stock time series): added a endpoint to fetch the market status
ricardo93borges/alphavantage-wrapper-ts pull request #56
Opened 2024-08-30 11:09 UTC by raozaeemshahid

A utility endpoint "Global Market Status" was missing in Core Stock APIs so added that.

2024-09-02 09:14 UTC, ricardo93borges requested changes
Please update the documentation with this new endpoint.

2024-09-02 09:14 UTC, ricardo93borges commented on src/stock-time-series/dto/market-status-response.dto.ts
> +  market_type: "Equity" | "Forex" | "Cryptocurrency";
please use enums for `market_type` and `current_status`

2024-09-06 22:09 UTC, raozaeemshahid commented
I've pushed the requested changes and also parse response to get the data in nice camel case.

2024-09-15 11:32 UTC, ricardo93borges commented
> I've pushed the requested changes and also parse response to get the data in nice camel case.

2024-09-15 11:32 UTC, ricardo93borges reviewed
Nice work, it is only missing the **unit tests** now.

2024-09-15 11:33 UTC, ricardo93borges requested changes
Nice work, it is only missing the unit tests now.

2025-12-16 16:48 UTC, closed without merging